### ISSUE TITLE
How do these files get deployed out to the live ganeti cluster?

### ISSUE THREAD

**Issue by gene1wood** [iocoop/iocoop-make-ganeti-vps#27]
How do these files get deployed out to the live ganeti cluster?

Should I manually put them on the ganeti hosts? @SuperQ thoughts?

**Comment by SuperQ** [comment]
This is deployed with Ansible.

https://github.com/iocoop/configs/blob/master/ansible/roles/ganeti/tasks/main.yml#L38-L41

Should be `ansible-playbook site.yml --limit ganeti -t ganeti`.
